spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never